# Generated by Django 5.2.7 on 2025-10-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='link_foto',
        ),
        migrations.AddField(
            model_name='produto',
            name='link_foto_ambiente',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto de Aplicação/Ambiente'),
        ),
        migrations.AddField(
            model_name='produto',
            name='link_foto_principal',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Foto Principal do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='acabamento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='detalhes',
            field=models.TextField(blank=True),
        ),
    ]
